version: '2'

services:
  app:
    build: ./app
    command: python -u app.py
    ports:
      - "5001:5001"
    networks:
      - sentiment_network
    environment:
      - SENTIMENT_SERVICE_URL=http://service:5002/

  service:
    build: ./sentiment_service
    command: python -u sentimentApp.py
    ports:
      - "5100:5002"
    networks:
      - sentiment_network

  db:
    image: mongo:latest
    hostname: sentiment_db
    ports:
      - "27017:27017"

    environment:
      - MONGO_INITDB_DATABASE=sentiments
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

    volumes:
      - sentiment_db:/data/db

volumes:
  sentiment_db:

networks:
  sentiment_network:
    driver: bridge