app:
  build: .

  command: python app.py

  ports:
    - "5000:5000"

  volumes:
   - .:/app
  links:
   - db

db:
  image: mongo:latest
  hostname: sentiment_db
  environment:
    - MONGO_INITDB_DATABASE=sentiment
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root

  ports:
    - "27017:27017"

  # volumes:  
    # - /data/db
